### ISSUE TITLE
"callFirst" error

### ISSUE THREAD

**Issue by fredrik-sogaard** [boboldehampsink/auditlog#10]
We get this error when we try to access the plugin:
```
Internal Server Error
Craft\PluginsService and its behaviors don not have a method or closure named "callFirst".
```
We are running Craft version 2.2.2601 (yeah, I know it's old but certain thing outside our control prevents us from updating)

Any idea why this is happening?

**Comment by boboldehampsink** [comment]
Yeah, callFirst was added in Craft 2.3 (http://buildwithcraft.com/updates#build2615) - you have to update in order to use this.
