### ISSUE TITLE
Plugin being maintained?

### ISSUE THREAD

**Issue by darylknight** [boboldehampsink/auditlog#21]
Just wanted to check in and firstly say thanks for all the work on this plugin, then secondly see what the plans for this plugin are, and whether it's still being maintained? Last update was a year ago, and there's an open issue about it not working on Craft 2.6. I love the idea and an audit log is REALLY useful on some client sites. If not, does anyone know of any alternatives or someone who might take over?

**Comment by szczups** [comment]
I'm interested in seeing this ported to upcoming Craft 3 version. @boboldehampsink do you think it's in the pipeline? Can I help somehow?

**Comment by boboldehampsink** [comment]
Hey. Currently I don't really have time to maintain it. Also, with Craft 3 coming up, there's little chance I will invest more time. A Craft 3 version might be developed once Craft 3 is out.
