### ISSUE TITLE
Not logging changes in Craft 2.3.2644

### ISSUE THREAD

**Issue by theartofpeople** [boboldehampsink/auditlog#8]
I've installed Auditlog and finding that its not logging any changes. 

If I click on the "Download CSV" button, it gives the error:

Parse error: syntax error, unexpected '[' in /home/www/clientdirectory/website/craft/plugins/auditlog/controllers/AuditLogController.php on line 70

**Comment by boboldehampsink** [comment]
What version of AuditLog are you using, and most of all: what PHP version are you using?

**Comment by theartofpeople** [comment]
Its PHP Version 5.3.10-1ubuntu3.7 and Auditlog 0.6.1. 

Logging into the CMS just now, it is displaying the changes from last week on the plugin screen. I still get the same php error when clicking on the "Download CSV" button.

**Comment by boboldehampsink** [comment]
It's probably caused by the low PHP version you run. I'll look into it, however you should think of upgrading to PHP 5.4 as the upcoming Craft 3 will not run on 5.3 ;-)
