### ISSUE TITLE
Error from Craft\AuditLogService->elementHasChanged

### ISSUE THREAD

**Issue by julzmon** [boboldehampsink/auditlog#9]
When saving an entry I get this error at times.

Seems to be an error coming from Craft\AuditLogService->elementHasChanged

![php notice](https://cloud.githubusercontent.com/assets/46877/10617741/03b81780-773a-11e5-8c73-a3da56af8d50.png)

**Comment by boboldehampsink** [comment]
Try 0.7.0

**Comment by julzmon** [comment]
It's been working great since the update. Thank you.
